"""
app.py
--------------------------------------------------------------------
Financial Fraud Detection Dashboard  (Streamlit + SQLite + Plotly)

This app reads the transactions generated by generate_data.py and runs
three SQL detection rules against them:

    1. Impossible Travel  - same user paying from two countries within 30 min
    2. Amount Anomaly     - a payment far above that user's own average
    3. Card Testing       - a burst of small failed payments, then a big success

All detection logic lives in SQL (section 2) so it can be lifted straight
into a data warehouse; Python is used only for presentation.

Run:  streamlit run app.py
--------------------------------------------------------------------
"""

import os
import sqlite3

import pandas as pd
import plotly.express as px
import streamlit as st

# =====================================================================
# 1. PAGE CONFIGURATION AND CORPORATE LIGHT THEME
# =====================================================================

DB_FILE = "transactions.db"

# Corporate palette: navy for structure, light blue for normal activity,
# red reserved exclusively for anomalies.
COLOR_NAVY = "#1F3B63"
COLOR_NORMAL = "#9EC5E8"    # light blue  -> legitimate transactions
COLOR_ALERT = "#D62728"     # red         -> anomalies
COLOR_ALERT_2 = "#E8743B"   # orange-red  -> second anomaly type
COLOR_ALERT_3 = "#A32020"   # dark red    -> third anomaly type

st.set_page_config(
    page_title="Fraud Detection Dashboard",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# A small amount of CSS to get a clean, business-like light layout:
# white cards for the KPIs, navy headings, quieter table borders.
st.markdown(
    """
    <style>
        .stApp { background-color: #F5F7FA; }

        h1, h2, h3 { color: #1F3B63; }

        /* KPI cards */
        div[data-testid="stMetric"] {
            background-color: #FFFFFF;
            border: 1px solid #E3E8EF;
            border-left: 4px solid #1F3B63;
            border-radius: 6px;
            padding: 16px 18px;
            box-shadow: 0 1px 2px rgba(16, 24, 40, 0.05);
        }
        div[data-testid="stMetricLabel"] p {
            color: #5A6B85;
            font-size: 0.82rem;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        div[data-testid="stMetricValue"] { color: #1F3B63; }

        /* Tabs */
        button[data-baseweb="tab"] { font-weight: 600; }

        section[data-testid="stSidebar"] { background-color: #FFFFFF; }
    </style>
    """,
    unsafe_allow_html=True,
)


# =====================================================================
# 2. SQL DETECTION RULES
# =====================================================================
# Each rule is a single, readable query built from simple CTEs and basic
# window functions. Every query returns one row per suspicious event,
# with the evidence an investigator needs to make a decision.

# ---------------------------------------------------------------------
# Rule 1 - Impossible Travel
# ---------------------------------------------------------------------
# Idea: sort each user's transactions by time, then use LAG() to look at
# their previous transaction. If the country changed but only a few
# minutes passed, the customer cannot physically have moved - so two
# different people are probably using the same account.
SQL_IMPOSSIBLE_TRAVEL = """
WITH user_movements AS (
    SELECT
        transaction_id,
        timestamp,
        user_id,
        ip_address,
        country,
        amount,
        LAG(country)   OVER (PARTITION BY user_id ORDER BY timestamp) AS previous_country,
        LAG(timestamp) OVER (PARTITION BY user_id ORDER BY timestamp) AS previous_timestamp
    FROM transactions
)
SELECT
    transaction_id,
    user_id,
    previous_country,
    country AS current_country,
    previous_timestamp,
    timestamp AS current_timestamp,
    -- julianday() returns days, so multiply by 24 * 60 to get minutes
    ROUND((julianday(timestamp) - julianday(previous_timestamp)) * 24 * 60, 1) AS minutes_between,
    amount,
    ip_address
FROM user_movements
WHERE previous_country IS NOT NULL              -- skip each user's first transaction
  AND country <> previous_country               -- the location changed
  AND (julianday(timestamp) - julianday(previous_timestamp)) * 24 * 60 <= 30
ORDER BY minutes_between ASC;
"""

# ---------------------------------------------------------------------
# Rule 2 - Amount Anomaly
# ---------------------------------------------------------------------
# Idea: compare every payment to the customer's OWN average, not to a
# global average. AVG() OVER (PARTITION BY user_id) puts that personal
# baseline next to each row, so one pass over the table is enough.
# Guard rails keep the alert list realistic:
#   * at least 5 transactions -> the average is meaningful
#   * at least 1,000 in value -> ignore trivial "5x of 2" cases
SQL_AMOUNT_ANOMALY = """
WITH user_spending AS (
    SELECT
        transaction_id,
        timestamp,
        user_id,
        country,
        ip_address,
        amount,
        AVG(amount) OVER (PARTITION BY user_id) AS user_avg_amount,
        COUNT(*)    OVER (PARTITION BY user_id) AS user_tx_count
    FROM transactions
    WHERE status = 'success'                    -- only money that actually moved
)
SELECT
    transaction_id,
    timestamp,
    user_id,
    country,
    ip_address,
    amount,
    ROUND(user_avg_amount, 2)          AS user_avg_amount,
    ROUND(amount / user_avg_amount, 1) AS times_above_average,
    user_tx_count
FROM user_spending
WHERE user_tx_count >= 5                        -- enough history to trust the average
  AND amount >= 1000                            -- material amount
  AND amount > 5 * user_avg_amount              -- 5x the customer's normal spend
ORDER BY times_above_average DESC;
"""

# ---------------------------------------------------------------------
# Rule 3 - Card Testing
# ---------------------------------------------------------------------
# Idea: describe the two halves of the attack in two small CTEs, then
# join them on the same user inside a 60-minute window.
#   failed_attempts -> the tiny probing payments that were declined
#   large_success   -> the cash-out once a working card is found
# HAVING COUNT(*) >= 3 makes sure we alert on a burst, not a single typo.
SQL_CARD_TESTING = """
WITH failed_attempts AS (
    SELECT user_id, timestamp, amount
    FROM transactions
    WHERE status = 'failed'
      AND amount < 20                           -- small "is this card alive?" probes
),
large_success AS (
    SELECT transaction_id, timestamp, user_id, country, ip_address, amount
    FROM transactions
    WHERE status = 'success'
      AND amount >= 500                         -- the cash-out
)
SELECT
    s.transaction_id,
    s.timestamp AS cashout_timestamp,
    s.user_id,
    s.country,
    s.ip_address,
    s.amount    AS cashout_amount,
    COUNT(*)    AS failed_attempts_before,
    ROUND(SUM(f.amount), 2) AS total_probed_amount,
    ROUND(MAX((julianday(s.timestamp) - julianday(f.timestamp)) * 24 * 60), 1) AS attack_window_minutes
FROM large_success AS s
JOIN failed_attempts AS f
      ON f.user_id   = s.user_id
     AND f.timestamp < s.timestamp              -- failures come first
     AND (julianday(s.timestamp) - julianday(f.timestamp)) * 24 * 60 <= 60
GROUP BY
    s.transaction_id, s.timestamp, s.user_id,
    s.country, s.ip_address, s.amount
HAVING COUNT(*) >= 3                            -- a burst of failures, not a one-off
ORDER BY failed_attempts_before DESC;
"""

SQL_ALL_TRANSACTIONS = """
SELECT transaction_id, timestamp, user_id, ip_address, country, amount, status
FROM transactions
ORDER BY timestamp;
"""


# =====================================================================
# 3. DATA ACCESS LAYER
# =====================================================================

@st.cache_data(show_spinner=False)
def run_query(sql: str) -> pd.DataFrame:
    """
    Execute one SQL statement against transactions.db and return a
    DataFrame. Results are cached so the queries run once per session
    instead of on every widget interaction.
    """
    with sqlite3.connect(DB_FILE) as connection:
        return pd.read_sql_query(sql, connection)


@st.cache_data(show_spinner=False)
def load_dashboard_data():
    """Run all four queries and label every transaction for the chart."""
    transactions = run_query(SQL_ALL_TRANSACTIONS)
    travel = run_query(SQL_IMPOSSIBLE_TRAVEL)
    amount = run_query(SQL_AMOUNT_ANOMALY)
    card = run_query(SQL_CARD_TESTING)

    transactions["timestamp"] = pd.to_datetime(transactions["timestamp"])

    # Tag each transaction with the rule that flagged it. A transaction can
    # in theory match more than one rule; the labels are applied in order of
    # investigation priority, so the last one written wins.
    transactions["anomaly_type"] = "Normal"
    for flagged_ids, label in [
        (amount["transaction_id"], "Amount Anomaly"),
        (card["transaction_id"], "Card Testing"),
        (travel["transaction_id"], "Impossible Travel"),
    ]:
        mask = transactions["transaction_id"].isin(flagged_ids)
        transactions.loc[mask, "anomaly_type"] = label

    return transactions, travel, amount, card


# =====================================================================
# 4. HEADER
# =====================================================================

st.title("🛡️ Financial Fraud Detection Dashboard")
st.markdown(
    "Rule-based monitoring of card payment activity. Every transaction is "
    "screened by three SQL detection rules — **Impossible Travel**, "
    "**Amount Anomaly** and **Card Testing** — and each alert below is "
    "presented with the supporting evidence an investigator needs to "
    "approve, block or escalate the case."
)

# Fail early and clearly if the database has not been generated yet.
if not os.path.exists(DB_FILE):
    st.error(
        f"Database '{DB_FILE}' was not found. "
        "Please run `python generate_data.py` first, then reload this page."
    )
    st.stop()

transactions, travel_df, amount_df, card_df = load_dashboard_data()

# =====================================================================
# 5. SIDEBAR - DETECTION RULE REFERENCE
# =====================================================================

with st.sidebar:
    st.header("Detection Rules")
    st.markdown(
        """
**1. Impossible Travel**
Country changes between two consecutive payments of the same user, less
than **30 minutes** apart.
*Signal: account takeover / shared credentials.*

---

**2. Amount Anomaly**
A successful payment above **5x the customer's own average** and at
least **1,000** in value (minimum 5 transactions of history).
*Signal: cash-out on a compromised account.*

---

**3. Card Testing**
**3 or more** failed payments under **20**, followed by a successful
payment of **500+** within **60 minutes**.
*Signal: stolen card enumeration.*
        """
    )
    st.caption(
        "Thresholds are the tuning surface of the system: tighten them to "
        "reduce analyst workload, loosen them to increase coverage."
    )

# =====================================================================
# 6. KPI METRICS
# =====================================================================

st.subheader("Portfolio Overview")

total_transactions = len(transactions)
flagged = transactions[transactions["anomaly_type"] != "Normal"]
total_anomalies = len(flagged)
amount_at_risk = flagged["amount"].sum()
anomaly_rate = (total_anomalies / total_transactions * 100) if total_transactions else 0

kpi1, kpi2, kpi3, kpi4 = st.columns(4)
kpi1.metric("Total Transactions", f"{total_transactions:,}")
kpi2.metric("Total Anomalies Found", f"{total_anomalies:,}")
kpi3.metric("Total Amount at Risk", f"${amount_at_risk:,.0f}")
kpi4.metric("Anomaly Rate", f"{anomaly_rate:.2f}%")

st.caption(
    f"Alert breakdown — Impossible Travel: {len(travel_df)} · "
    f"Amount Anomaly: {len(amount_df)} · Card Testing: {len(card_df)}. "
    "Amount at risk counts each flagged transaction once, even when it "
    "triggers more than one rule."
)

st.divider()

# =====================================================================
# 7. SCATTER PLOT - TRANSACTIONS OVER TIME
# =====================================================================

st.subheader("Transaction Activity Over Time")

chart_left, chart_right = st.columns([3, 1])
with chart_right:
    log_scale = st.toggle(
        "Logarithmic amount axis",
        value=True,
        help="Most payments are small. A log scale keeps the normal "
             "population readable while extreme amounts stay visible.",
    )
    show_normal = st.toggle("Show normal transactions", value=True)

plot_data = transactions if show_normal else flagged

# Category order controls drawing order, so anomalies are painted on top
# of the light-blue background of normal activity.
color_map = {
    "Normal": COLOR_NORMAL,
    "Amount Anomaly": COLOR_ALERT,
    "Card Testing": COLOR_ALERT_2,
    "Impossible Travel": COLOR_ALERT_3,
}
category_order = ["Normal", "Amount Anomaly", "Card Testing", "Impossible Travel"]

fig = px.scatter(
    plot_data,
    x="timestamp",
    y="amount",
    color="anomaly_type",
    color_discrete_map=color_map,
    category_orders={"anomaly_type": [c for c in category_order
                                      if c in set(plot_data["anomaly_type"])]},
    log_y=log_scale,
    opacity=0.75,
    labels={"timestamp": "Date", "amount": "Amount ($)", "anomaly_type": "Classification"},
    hover_data={"user_id": True, "country": True, "status": True, "transaction_id": True},
    template="plotly_white",
    height=480,
)
fig.update_traces(marker=dict(size=6, line=dict(width=0)))
# Make the anomalies visually louder than the normal background
fig.for_each_trace(
    lambda trace: trace.update(marker=dict(size=10, symbol="diamond",
                                           line=dict(width=1, color="#FFFFFF")))
    if trace.name != "Normal" else None
)
fig.update_layout(
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1,
                title_text=""),
    margin=dict(l=10, r=10, t=40, b=10),
    plot_bgcolor="#FFFFFF",
    paper_bgcolor="#FFFFFF",
    font=dict(color="#33415C"),
    hovermode="closest",
)
fig.update_xaxes(gridcolor="#EDF1F7")
fig.update_yaxes(gridcolor="#EDF1F7")

st.plotly_chart(fig, width="stretch")

st.divider()

# =====================================================================
# 8. INVESTIGATION TABLES
# =====================================================================

st.subheader("Alert Queues for Investigation")

tab1, tab2, tab3 = st.tabs([
    f"🌍 Impossible Travel ({len(travel_df)})",
    f"💸 Amount Anomaly ({len(amount_df)})",
    f"🔁 Card Testing ({len(card_df)})",
])

# --- Tab 1: Impossible Travel ----------------------------------------
with tab1:
    st.markdown(
        "**What triggers this alert:** the same `user_id` pays from one "
        "country and then from a different country less than 30 minutes "
        "later. `LAG()` supplies the previous country and timestamp for "
        "each user, so the comparison is a single pass over the table."
    )
    st.dataframe(
        travel_df,
        width="stretch",
        hide_index=True,
        column_config={
            "transaction_id": st.column_config.NumberColumn("Txn ID", format="%d"),
            "user_id": "User",
            "previous_country": "From",
            "current_country": "To",
            "previous_timestamp": "Previous Time",
            "current_timestamp": "Alert Time",
            "minutes_between": st.column_config.NumberColumn("Minutes Apart", format="%.1f"),
            "amount": st.column_config.NumberColumn("Amount", format="$%.2f"),
            "ip_address": "IP Address",
        },
    )

# --- Tab 2: Amount Anomaly -------------------------------------------
with tab2:
    st.markdown(
        "**What triggers this alert:** a successful payment more than 5x "
        "the customer's own average, and at least \\$1,000. "
        "`AVG(amount) OVER (PARTITION BY user_id)` places each customer's "
        "personal baseline next to every one of their transactions."
    )
    st.dataframe(
        amount_df,
        width="stretch",
        hide_index=True,
        column_config={
            "transaction_id": st.column_config.NumberColumn("Txn ID", format="%d"),
            "timestamp": "Time",
            "user_id": "User",
            "country": "Country",
            "ip_address": "IP Address",
            "amount": st.column_config.NumberColumn("Amount", format="$%.2f"),
            "user_avg_amount": st.column_config.NumberColumn("User Average", format="$%.2f"),
            "times_above_average": st.column_config.NumberColumn("x Above Average", format="%.1fx"),
            "user_tx_count": st.column_config.NumberColumn("User Txn Count", format="%d"),
        },
    )

# --- Tab 3: Card Testing ---------------------------------------------
with tab3:
    st.markdown(
        # Dollar signs are escaped: a pair of unescaped '$' in Streamlit
        # markdown is interpreted as LaTeX math and swallows the text between.
        "**What triggers this alert:** 3 or more failed payments under \\$20 "
        "from the same user, followed within 60 minutes by a successful "
        "payment of \\$500 or more. The two halves of the attack are defined "
        "as separate CTEs and joined on user and time window."
    )
    st.dataframe(
        card_df,
        width="stretch",
        hide_index=True,
        column_config={
            "transaction_id": st.column_config.NumberColumn("Txn ID", format="%d"),
            "cashout_timestamp": "Cash-out Time",
            "user_id": "User",
            "country": "Country",
            "ip_address": "IP Address",
            "cashout_amount": st.column_config.NumberColumn("Cash-out Amount", format="$%.2f"),
            "failed_attempts_before": st.column_config.NumberColumn("Failed Probes", format="%d"),
            "total_probed_amount": st.column_config.NumberColumn("Probed Value", format="$%.2f"),
            "attack_window_minutes": st.column_config.NumberColumn("Window (min)", format="%.1f"),
        },
    )

# =====================================================================
# 9. FOOTER
# =====================================================================

st.divider()
st.caption(
    "Data source: transactions.db (10,000 synthetic transactions generated "
    "by generate_data.py). Detection logic is implemented entirely in SQL "
    "so it can be deployed directly against a production data warehouse."
)
